In [1]:
import numpy as np
import pandas as pd

In [3]:
messy_data = pd.DataFrame({'location': ['       USA, north america','  China,asia','India, asia  ', 'Russia, Asia   ','France,     europe','UK, europe'],
            'national_day': ['July 4, 1776','October 1, 1949','August 15, 1947','June 12, 1990','July 14, 1789',"Not available"],
            'national_day_alt': ['4/7/1776','1/10/1949','15/8/1947','12/6/1990','14/7/1789',"Not available"],
            'per_capita_dollars': ['$65,280.70','$10,261.70','$2,104.10','$11,585.00','$40,493.90','$42,300.30'],
            'per_capita_euros': ['55 488,59 €','8 722,44 €','1 788,48 €','9 847,25 €','34 419,82 €','35 955,26 €'],
            'population': [2,2,2,1,1,1]})
messy_data

location     national_day national_day_alt  \
0         USA, north america     July 4, 1776         4/7/1776   
1                 China,asia  October 1, 1949        1/10/1949   
2              India, asia    August 15, 1947        15/8/1947   
3            Russia, Asia       June 12, 1990        12/6/1990   
4         France,     europe    July 14, 1789        14/7/1789   
5                 UK, europe    Not available    Not available   

  per_capita_dollars per_capita_euros  population  
0         $65,280.70      55 488,59 €           2  
1         $10,261.70       8 722,44 €           2  
2          $2,104.10       1 788,48 €           2  
3         $11,585.00       9 847,25 €           1  
4         $40,493.90      34 419,82 €           1  
5         $42,300.30      35 955,26 €           1

In [4]:
messy_data.dtypes

location              object
national_day          object
national_day_alt      object
per_capita_dollars    object
per_capita_euros      object
population             int64
dtype: object

messy_data.national_day.re

In [6]:
messy_data.national_day.replace('Not available',None)

0       July 4, 1776
1    October 1, 1949
2    August 15, 1947
3      June 12, 1990
4      July 14, 1789
5               None
Name: national_day, dtype: object

In [32]:
messy_data.national_day=pd.to_datetime(messy_data.national_day,format='%B %d, %Y')

In [33]:
messy_data

location national_day national_day_alt per_capita_dollars  \
0         USA, north america   1776-07-04         4/7/1776         $65,280.70   
1                 China,asia   1949-10-01        1/10/1949         $10,261.70   
2              India, asia     1947-08-15        15/8/1947          $2,104.10   
3            Russia, Asia      1990-06-12        12/6/1990         $11,585.00   
4         France,     europe   1789-07-14        14/7/1789         $40,493.90   
5                 UK, europe          NaT    Not available         $42,300.30   

  per_capita_euros  population  
0      55 488,59 €           2  
1       8 722,44 €           2  
2       1 788,48 €           2  
3       9 847,25 €           1  
4      34 419,82 €           1  
5      35 955,26 €           1

In [34]:
messy_data.national_day_alt=pd.to_datetime(messy_data.national_day_alt.replace('Not available',None),format='%d/%m/%Y')

In [35]:
messy_data

location national_day national_day_alt per_capita_dollars  \
0         USA, north america   1776-07-04       1776-07-04         $65,280.70   
1                 China,asia   1949-10-01       1949-10-01         $10,261.70   
2              India, asia     1947-08-15       1947-08-15          $2,104.10   
3            Russia, Asia      1990-06-12       1990-06-12         $11,585.00   
4         France,     europe   1789-07-14       1789-07-14         $40,493.90   
5                 UK, europe          NaT              NaT         $42,300.30   

  per_capita_euros  population  
0      55 488,59 €           2  
1       8 722,44 €           2  
2       1 788,48 €           2  
3       9 847,25 €           1  
4      34 419,82 €           1  
5      35 955,26 €           1

In [38]:
messy_data.national_day.dt.day_name()

0    Thursday
1    Saturday
2      Friday
3     Tuesday
4     Tuesday
5         NaN
Name: national_day, dtype: object

In [40]:
messy_data.per_capita_dollars=messy_data.per_capita_dollars.str.removeprefix('$').str.replace(',','').astype('float64')

In [58]:
country=messy_data.location.str.split(',',expand=True)[0].str.strip().str.title()
continent=messy_data.location.str.split(',',expand=True)[1].str.strip().str.title()

In [63]:
messy_data['country']=country
messy_data['continent']=continent

In [64]:
messy_data

location national_day national_day_alt  \
0         USA, north america   1776-07-04       1776-07-04   
1                 China,asia   1949-10-01       1949-10-01   
2              India, asia     1947-08-15       1947-08-15   
3            Russia, Asia      1990-06-12       1990-06-12   
4         France,     europe   1789-07-14       1789-07-14   
5                 UK, europe          NaT              NaT   

   per_capita_dollars per_capita_euros  population country      continent  
0             65280.7      55 488,59 €           2     Usa  North America  
1             10261.7       8 722,44 €           2   China           Asia  
2              2104.1       1 788,48 €           2   India           Asia  
3             11585.0       9 847,25 €           1  Russia           Asia  
4             40493.9      34 419,82 €           1  France         Europe  
5             42300.3      35 955,26 €           1      Uk         Europe

In [69]:
import os
os.getcwd()

'C:\\Users\\athar\\myfiles'

In [70]:
ufo=pd.read_csv('ufo.csv')
ufo


reported_date_time                                            summary
0     2021-12-14 04:30:00                            No Sighting, only sound
1     2021-12-04 00:14:00  Sighted an odd object in the sky, in the landi...
2     2021-11-16 07:50:00  ((NUFORC Note:  Witness provides no informatio...
3     2021-11-02 02:00:00  Glowing orbs changing color and staying in pla...
4     2021-11-01 04:00:00  About 9:00 pm Local time saw a bright Fluoresc...
...                   ...                                                ...
1819  2021-01-24 12:10:00  Brilliantly lit flat object of large size seem...
1820  2021-01-08 04:30:00  Huge city block length sighting in Marietta Oh...
1821  2021-01-04 04:00:00  Bright, flashing multi colored lights coming f...
1822  2021-01-02 03:48:00  Walking my dog & began filming with my iPhone ...
1823  2021-02-01 13:24:00        Straight line of lights in sky moving east,

[1824 rows x 2 columns]

In [71]:
ufo['reported_date_time'] = pd.to_datetime(ufo.reported_date_time, format = 'mixed')
ufo['year'] = ufo.reported_date_time.dt.year
ufo['month'] = ufo.reported_date_time.dt.month
ufo['day'] = ufo.reported_date_time.dt.day
ufo['weekday'] = ufo.reported_date_time.dt.day_name()
ufo['hour'] = ufo.reported_date_time.dt.hour
ufo['minute'] = ufo.reported_date_time.dt.minute
ufo['second'] = ufo.reported_date_time.dt.second
ufo['bright'] = ufo.summary.str.contains(pat = 'bright')
ufo['craft'] = ufo.summary.str.contains(pat = 'craft')
ufo['light'] = ufo.summary.str.contains(pat = 'light')
ufo.head()

reported_date_time                                            summary  \
0 2021-12-14 04:30:00                            No Sighting, only sound   
1 2021-12-04 00:14:00  Sighted an odd object in the sky, in the landi...   
2 2021-11-16 07:50:00  ((NUFORC Note:  Witness provides no informatio...   
3 2021-11-02 02:00:00  Glowing orbs changing color and staying in pla...   
4 2021-11-01 04:00:00  About 9:00 pm Local time saw a bright Fluoresc...   

   year  month  day   weekday  hour  minute  second bright  craft  light  
0  2021     12   14   Tuesday     4      30       0  False  False  False  
1  2021     12    4  Saturday     0      14       0  False  False  False  
2  2021     11   16   Tuesday     7      50       0  False  False  False  
3  2021     11    2   Tuesday     2       0       0  False  False  False  
4  2021     11    1    Monday     4       0       0   True  False  False

In [72]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [73]:
np.random.seed(1031)
gender = np.random.choice(['Male','Female'],size = 10,replace = True)
age_group = np.random.choice(['18-29','30-39','40-49','50-59','60 or over'],size = 10,replace=True)
marital_status = np.random.choice(['married','married','widowed','divorced','separated','never married','never married'],size = 10,replace = True)
ethnicity = np.random.choice(['White','Black','Native','Asian','Hispanic','Other'],size = 10,replace = True)
zip_code = np.random.randint(10000,10055,10)
cat_demo = pd.DataFrame({'gender':gender, 
             'age_group':age_group,
             'marital_status': marital_status,
             'ethnicity': ethnicity,
             'zip_code': zip_code})
cat_demo

gender   age_group marital_status ethnicity  zip_code
0  Female       18-29       divorced     Other     10003
1    Male       30-39  never married    Native     10051
2  Female       30-39        married     White     10033
3    Male  60 or over      separated     Black     10025
4  Female       18-29  never married     White     10023
5    Male       30-39        widowed     White     10036
6    Male  60 or over        married     Black     10036
7  Female       18-29  never married     White     10033
8  Female  60 or over  never married     White     10010
9    Male       30-39  never married     Asian     10001

In [75]:
cat_demo.gender.value_counts()

gender
Female    5
Male      5
Name: count, dtype: int64

In [79]:
pd.get_dummies(cat_demo.gender,drop_first=True)

Male
0  False
1   True
2  False
3   True
4  False
5   True
6   True
7  False
8  False
9   True

In [80]:
pd.get_dummies(cat_demo.age_group,drop_first=False)

18-29  30-39  60 or over
0   True  False       False
1  False   True       False
2  False   True       False
3  False  False        True
4   True  False       False
5  False   True       False
6  False  False        True
7   True  False       False
8  False  False        True
9  False   True       False

In [82]:
pd.get_dummies(cat_demo.marital_status,drop_first=True)

married  never married  separated  widowed
0    False          False      False    False
1    False           True      False    False
2     True          False      False    False
3    False          False       True    False
4    False           True      False    False
5    False          False      False     True
6     True          False      False    False
7    False           True      False    False
8    False           True      False    False
9    False           True      False    False

In [84]:
marital_counts=counts = cat_demo.marital_status.value_counts()
sparse_categories = marital_counts[counts<2].index
cat_demo['marital_status'] = cat_demo.marital_status.replace(sparse_categories,'other')
cat_demo

gender   age_group marital_status ethnicity  zip_code
0  Female       18-29          other     Other     10003
1    Male       30-39  never married    Native     10051
2  Female       30-39        married     White     10033
3    Male  60 or over          other     Black     10025
4  Female       18-29  never married     White     10023
5    Male       30-39          other     White     10036
6    Male  60 or over        married     Black     10036
7  Female       18-29  never married     White     10033
8  Female  60 or over  never married     White     10010
9    Male       30-39  never married     Asian     10001

In [86]:
from sklearn.preprocessing import StandardScaler

In [87]:
fastfood=pd.read_csv('fastfood.csv')
fastfood

id  health1  health2  health3  mcdonalds  chipotle  shake_shack  \
0        1        1        1        1          6         7            3   
1        2        6        3        5          5         7            4   
2        3        4        3        4          4         2            7   
3        4        1        1        1          1         4            3   
4        5        1        1        1          7         3            1   
...    ...      ...      ...      ...        ...       ...          ...   
1995  1996        2        1        1          3         1            2   
1996  1997        2        1        1          2         2            6   
1997  1998        7        2        3          1         4            5   
1998  1999        4        1        1          3         3            7   
1999  2000        3        1        1          3         5            5   

      gender    age marital_status    location    duration  rank_chipotle  \
0       Male  18-29  never married   Manhattan  119.338299              3   
1     Female  50-59  never married  New Jersey  221.970589              3   
2     Female  30-39  never married    Brooklyn  260.713333              1   
3       Male  40-49        married    Brooklyn  146.267609              3   
4     Female  30-39  never married    Brooklyn  235.987555              2   
...      ...    ...            ...         ...         ...            ...   
1995    Male  18-29  never married   Manhattan  226.489953              1   
1996  Female  18-29        married   Manhattan  268.335581              2   
1997    Male  18-29      separated   Manhattan  254.454988              2   
1998    Male  30-39        married      Queens  170.940982              2   
1999  Female  40-49        married    Brooklyn  136.711617              2   

      rank_mcdonalds  rank_shake_shack  
0                  2                 1  
1                  2                 1  
2                  2                 3  
3                  1                 2  
4                  3                 1  
...              ...               ...  
1995               3                 2  
1996               1                 3  
1997               1                 3  
1998               1                 3  
1999               1                 3  

[2000 rows x 15 columns]

In [89]:
fastfood.chipotle.describe()

count    2000.000000
mean        3.994500
std         1.739535
min         1.000000
25%         3.000000
50%         4.000000
75%         5.000000
max         7.000000
Name: chipotle, dtype: float64

In [90]:
scaler=StandardScaler()

In [93]:
chipotle_scaled=scaler.fit_transform(fastfood[['chipotle']])

In [98]:
from sklearn.feature_selection import VarianceThreshold
low_var = VarianceThreshold(threshold=0.1)
fastfood_likert = fastfood.loc[:,'health1':'shake_shack']
fastfood_likert_reduced = low_var.fit_transform(fastfood_likert)
fastfood_likert_reduced

array([[1, 1, 1, 6, 7, 3],
       [6, 3, 5, 5, 7, 4],
       [4, 3, 4, 4, 2, 7],
       ...,
       [7, 2, 3, 1, 4, 5],
       [4, 1, 1, 3, 3, 7],
       [3, 1, 1, 3, 5, 5]], dtype=int64)

In [99]:
from sklearn.preprocessing import MinMaxScaler
min_max_normal = MinMaxScaler(feature_range=(0,1))
min_max_normal.fit_transform(fastfood.loc[:,'health1':'health3'])

array([[0.        , 0.        , 0.        ],
       [0.83333333, 0.33333333, 0.66666667],
       [0.5       , 0.33333333, 0.5       ],
       ...,
       [1.        , 0.16666667, 0.33333333],
       [0.5       , 0.        , 0.        ],
       [0.33333333, 0.        , 0.        ]])

This uses an operation similar to logarithm

In [100]:
from sklearn.preprocessing import PowerTransformer
box_cox = PowerTransformer('box-cox')
box_cox_duration = box_cox.fit_transform(fastfood.loc[:,['duration']])
box_cox_duration.reshape(2000,)

array([-1.69425898,  0.3497455 ,  0.90356725, ...,  0.81927213,
       -0.52824732, -1.25885183])

In [101]:
from sklearn.preprocessing import PolynomialFeatures
poly_features = PolynomialFeatures(degree = 2, include_bias=False, interaction_only=False)
poly_features.fit_transform(fastfood.loc[:,'health1':'health2'])

array([[ 1.,  1.,  1.,  1.,  1.],
       [ 6.,  3., 36., 18.,  9.],
       [ 4.,  3., 16., 12.,  9.],
       ...,
       [ 7.,  2., 49., 14.,  4.],
       [ 4.,  1., 16.,  4.,  1.],
       [ 3.,  1.,  9.,  3.,  1.]])

In [102]:
import pandas as pd

customers = pd.DataFrame({'customer_id': [1, 2, 3, 4, 5],
              'name': ["John Doe", "Jane Smith", "Emily Johnson", "Michael Brown", "Jessica Williams"],
              'email': ["john@example.com", "jane@example.com", "emily@example.com", "michael@example.com", "jessica@example.com"]})

transactions = pd.DataFrame({'transaction_id': [1001, 1002, 1003, 1004, 1005],
              'customer_id': [1, 2, 1, 4, 5],
              'amount':[250.75, 100.50, 320.00, 450.25, 500.00],
              'transaction_date': ['2023-01-15', '2023-02-10', '2023-02-20', '2023-03-05', '2023-03-15']})
transactions['transactions_date'] = pd.to_datetime(transactions.transaction_date)

In [103]:
import pandas as pd
gdp = pd.DataFrame({'country': ['USA','China','Japan'],
                    '1960': [543300, 59716, 44307],
                    '2017': [19390604, 12237700, 4872136]})
gdp

country    1960      2017
0     USA  543300  19390604
1   China   59716  12237700
2   Japan   44307   4872136

In [104]:
pd.melt(gdp)

variable     value
0  country       USA
1  country     China
2  country     Japan
3     1960    543300
4     1960     59716
5     1960     44307
6     2017  19390604
7     2017  12237700
8     2017   4872136

In [113]:
unpivoted=pd.melt(gdp,id_vars='country',value_name='gdp',var_name='year')
pd.melt(gdp,id_vars='country',value_name='gdp',var_name='year')

country  year       gdp
0     USA  1960    543300
1   China  1960     59716
2   Japan  1960     44307
3     USA  2017  19390604
4   China  2017  12237700
5   Japan  2017   4872136

In [115]:
pd.pivot(unpivoted,columns='year',index='country')

gdp          
year       1960      2017
country                  
China     59716  12237700
Japan     44307   4872136
USA      543300  19390604